In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("~/assignment/505-olympics-mini-project/files/olympics.csv" )
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,# Summer,01 !,02 !,03 !,Total,# Winter,01 !,02 !,03 !,Total,# Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
5,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
6,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
7,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
8,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
9,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
10,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
11,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
12,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
13,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
14,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
15,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
16,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
17,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
18,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
19,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
20,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
21,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
22,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
23,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
24,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
25,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
26,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
27,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
28,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
29,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
119,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
120,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
121,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
122,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
123,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
124,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
125,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
126,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
127,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
128,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
129,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
130,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
131,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
132,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
133,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
134,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
135,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
136,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
137,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
138,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
139,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
140,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
141,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
142,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [2]:
def load_data():
    df = pd.read_csv("~/assignment/505-olympics-mini-project/files/olympics.csv",  skiprows=[1])
    
    df= df.rename(columns = {'0':'country', '1':'NOGS', '2':'Sum_Gold', '3':'Sum_Silver', 
                             '4':'Sum_Bronze', '5': 'Totals', '6':'NOGW', '7':'Win_Gold',
                             '8':'Win_Silver', '9':'Win_Bronze','10': 'Totals', 
                             '11':'NOGCombined', '12':'Com_Gold', '13':'Com_Silver', 
                             '14':'Com_Bronze', '15': 'Totals'})
    
    value = df['country'].str.split('(', expand=True)[0]#Split country name and country code and add 
    #country name as data frame index
    
    df = df.set_index(value)
    df = df.drop('country', axis=1)
    df = df.drop('Totals', axis=1)#Drop the Column Totals 
    df = df.drop('Totals')#Drop the row Totals 
    
    return df

In [3]:
#data cleanup

load_data()

,NOGS,Sum_Gold,Sum_Silver,Sum_Bronze,NOGW,Win_Gold,Win_Silver,Win_Bronze,NOGCombined,Com_Gold,Com_Silver,Com_Bronze
0,,,,,,,,,,,,
Afghanistan,13,0,0,2,0,0,0,0,13,0,0,2
Algeria,12,5,2,8,3,0,0,0,15,5,2,8
Argentina,23,18,24,28,18,0,0,0,41,18,24,28
Armenia,5,1,2,9,6,0,0,0,11,1,2,9
Australasia,2,3,4,5,0,0,0,0,2,3,4,5
Australia,25,139,152,177,18,5,3,4,43,144,155,181
Austria,26,18,33,35,22,59,78,81,48,77,111,116
Azerbaijan,5,6,5,15,5,0,0,0,10,6,5,15
Bahamas,15,5,2,5,0,0,0,0,15,5,2,5
Bahrain,8,0,0,1,0,0,0,0,8,0,0,1
Barbados,11,0,0,1,0,0,0,0,11,0,0,1
Belarus,5,12,24,39,6,6,4,5,11,18,28,44
Belgium,25,37,52,53,20,1,1,3,45,38,53,56
Bermuda,17,0,0,1,7,0,0,0,24,0,0,1
Bohemia,3,0,1,3,0,0,0,0,3,0,1,3
Botswana,9,0,1,0,0,0,0,0,9,0,1,0
Brazil,21,23,30,55,7,0,0,0,28,23,30,55
British West Indies,1,0,0,2,0,0,0,0,1,0,0,2
Bulgaria,19,51,85,78,19,1,2,3,38,52,87,81
Burundi,5,1,0,0,0,0,0,0,5,1,0,0
Cameroon,13,3,1,1,1,0,0,0,14,3,1,1
Canada,25,59,99,121,22,62,56,52,47,121,155,173
Chile,22,2,7,4,16,0,0,0,38,2,7,4
China,9,201,146,126,10,12,22,19,19,213,168,145
Colombia,18,2,6,11,1,0,0,0,19,2,6,11
Costa Rica,14,1,1,2,6,0,0,0,20,1,1,2
Ivory Coast,12,0,1,0,0,0,0,0,12,0,1,0
Croatia,6,6,7,10,7,4,6,1,13,10,13,11
Cuba,19,72,67,70,0,0,0,0,19,72,67,70
Cyprus,9,0,1,0,10,0,0,0,19,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
Spain,22,37,59,35,19,1,0,1,41,38,59,36
Sri Lanka,16,0,2,0,0,0,0,0,16,0,2,0
Sudan,11,0,1,0,0,0,0,0,11,0,1,0
Suriname,11,1,0,1,0,0,0,0,11,1,0,1
Sweden,26,143,164,176,22,50,40,54,48,193,204,230
Switzerland,27,47,73,65,22,50,40,48,49,97,113,113
Syria,12,1,1,1,0,0,0,0,12,1,1,1
Chinese Taipei,13,2,7,12,11,0,0,0,24,2,7,12
Tajikistan,5,0,1,2,4,0,0,0,9,0,1,2
Tanzania,12,0,2,0,0,0,0,0,12,0,2,0
Thailand,15,7,6,11,3,0,0,0,18,7,6,11
Togo,9,0,0,1,1,0,0,0,10,0,0,1
Tonga,8,0,1,0,1,0,0,0,9,0,1,0
Trinidad and Tobago,16,2,5,11,3,0,0,0,19,2,5,11
Tunisia,13,3,3,4,0,0,0,0,13,3,3,4
Turkey,21,39,25,24,16,0,0,0,37,39,25,24
Uganda,14,2,3,2,0,0,0,0,14,2,3,2
Ukraine,5,33,27,55,6,2,1,4,11,35,28,59
United Arab Emirates,8,1,0,0,0,0,0,0,8,1,0,0
United States,26,976,757,666,22,96,102,84,48,1072,859,750
Uruguay,20,2,2,6,1,0,0,0,21,2,2,6
Uzbekistan,5,5,5,10,6,1,0,0,11,6,5,10
Venezuela,17,2,2,8,4,0,0,0,21,2,2,8
Vietnam,14,0,2,0,0,0,0,0,14,0,2,0
Virgin Islands,11,0,1,0,7,0,0,0,18,0,1,0
Yugoslavia,16,26,29,28,14,0,3,1,30,26,32,29
Independent Olympic Participants,1,0,1,2,0,0,0,0,1,0,1,2
Zambia,12,0,1,1,0,0,0,0,12,0,1,1
Zimbabwe,12,3,4,1,1,0,0,0,13,3,4,1
Mixed team,3,8,5,4,0,0,0,0,3,8,5,4

In [4]:
def first_country():
    df = load_data()
    
    return df.head(1)

In [5]:
#first country details from dataframe we got from load_data function.
first_country()

,NOGS,Sum_Gold,Sum_Silver,Sum_Bronze,NOGW,Win_Gold,Win_Silver,Win_Bronze,NOGCombined,Com_Gold,Com_Silver,Com_Bronze
0,,,,,,,,,,,,
Afghanistan,13,0,0,2,0,0,0,0,13,0,0,2

In [6]:
#country who won most gold medals.

def gold_medal():
    df = load_data()

    return df.Sum_Gold.argmax()

In [7]:
gold_medal() #country who won most gold medals. in all seasons

'United States\xa0'

In [8]:
string = gold_medal()
string = string.replace(u'\xa0', u' ')
string

'United States '

In [9]:
def biggest_difference_in_gold_medal():
    df = load_data()
    return (df.Sum_Gold - df.Win_Gold).abs().argmax()

In [10]:
biggest_difference_in_gold_medal()#biggest_difference_in_gold_medal to get name of country
#who has biggest difference between their summer and winter gold medal counts.

'United States\xa0'

In [11]:
string = biggest_difference_in_gold_medal()
string = string.replace(u'\xa0', u' ')
string

'United States '

In [12]:
#Return dataframe with points column and index.

def get_points():
    df = load_data()
    points = np.zeros(len(df))
    points += df.Com_Gold * 3
    points += df.Com_Silver * 2
    points += df.Com_Bronze
    return pd.Series(points, index=df.index).apply(int) #.appy(int) Series from float to integer

In [13]:
Points = get_points()

In [14]:
Points

0
Afghanistan                             2
Algeria                                27
Argentina                             130
Armenia                                16
Australasia                            22
Australia                             923
Austria                               569
Azerbaijan                             43
Bahamas                                24
Bahrain                                 1
Barbados                                1
Belarus                               154
Belgium                               276
Bermuda                                 1
Bohemia                                 5
Botswana                                2
Brazil                                184
British West Indies                     2
Bulgaria                              411
Burundi                                 3
Cameroon                               12
Canada                                846
Chile                                  24
China                                1120
Colombia                               29
Costa Rica                              7
Ivory Coast                             2
Croatia                                67
Cuba                                  420
Cyprus                                  2
                                     ...
Spain                                 268
Sri Lanka                               4
Sudan                                   2
Suriname                                4
Sweden                               1217
Switzerland                           630
Syria                                   6
Chinese Taipei                         32
Tajikistan                              4
Tanzania                                4
Thailand                               44
Togo                                    1
Tonga                                   2
Trinidad and Tobago                    27
Tunisia                                19
Turkey                                191
Uganda                                 14
Ukraine                               220
United Arab Emirates                    3
United States                        5684
Uruguay                                16
Uzbekistan                             38
Venezuela                              18
Vietnam                                 4
Virgin Islands                          2
Yugoslavia                            171
Independent Olympic Participants        4
Zambia                                  3
Zimbabwe                               18
Mixed team                             38
Length: 146, dtype: int64